apply plugin: 'com.android.application'

android {
    compileSdkVersion 36
    defaultConfig {
        applicationId "lk.pitaka.books"
        minSdkVersion 21
        targetSdkVersion 36
        versionCode 20
        versionName "2.0"
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    namespace 'lk.pitaka.books'

    // copy the jathaka-images folder to the jathaka_images_asset/src/main/assets
    // to reduce the file sizes for mobile
    // magick mogrify -path mobile -resize x384 -quality 80 -strip *.jpeg
    assetPacks = [":jathaka_images_asset"]
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
}